/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperJson Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperJson.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  schema.json file and rebuild the project.
 * --------------------------------------------------------
 */

declare module "@indago/hyper-json" {
  interface LanguageContentSchema {
    items?: Language[];
  }
  interface Language {
    id: string;
    name: string;
    nativeName: string;
    flag: string;
    emojiFlag: string;
    proficiency:
      | "Native"
      | "Advanced"
      | "Upper Intermediate"
      | "Intermediate"
      | "Basic"
      | "Beginner";
    color: string;
    levels: LanguageProficiency;
  }
  interface LanguageProficiency {
    speaking?: number;
    listening?: number;
    reading?: number;
  }
}
