/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperDown Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperDown.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  frontmatter.json file and rebuild the project.
 * --------------------------------------------------------
 */

import { createLazyRepository } from "@muttum/hyper-down/server";

import type { ArticleMeta } from "@muttum/hyper-down";

// Server-only DAO for the `article` collection — imported by `+data.ts`
// loaders (SSR-only), never by browser code. Lazily instantiated.
export const articleRepository = createLazyRepository<ArticleMeta>({
  contentName: "article",
});
