/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperDown Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperDown.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  frontmatter.json file and rebuild the project.
 * --------------------------------------------------------
 */

import type { ContentMeta } from "@muttum/hyper-down/types";

declare module "@muttum/hyper-down" {
  export interface ArticleMeta extends ContentMeta {
    title: string;
    description?: string;
    date: string;
    preview?: string;
    draft?: boolean;
    tags?: string[];
    categories?: string[];
    author?: string;
    readingTime?: string;
    canonical?: string;
    cover?: string;
  }
}
