/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperDown Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperDown.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  frontmatter.json file and rebuild the project.
 * --------------------------------------------------------
 */

import articleModules from "./content/article/modules";
import recipeModules from "./content/recipe/modules";

export const contentModules = {
  article: articleModules,
  recipe: recipeModules,
};

/** Union of the content-type names, e.g. `"article" | "recipe"`. */
export type ContentType = keyof typeof contentModules;
