/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperDown Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperDown.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  frontmatter.json file and rebuild the project.
 * --------------------------------------------------------
 */

import type { ContentModuleMap } from "@indago/hyper-down/types";

// Draft items are excluded so their MD/MDX is never compiled or shipped.
export default import.meta.glob([
  "/content/recipe/**/*.mdx",
  "!/content/recipe/en/chicken-catupiry-pancakes.mdx",
  "!/content/recipe/pt-BR/chicken-catupiry-pancakes.mdx",
], { eager: true }) as ContentModuleMap;
