/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperDown Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperDown.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  frontmatter.json file and rebuild the project.
 * --------------------------------------------------------
 */

import type { ContentModuleMap } from "@muttum/hyper-down/types";

export default import.meta.glob("/content/recipe/**/*.mdx", { eager: true }) as ContentModuleMap;
