/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperJson Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperJson.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  schema.json file and rebuild the project.
 * --------------------------------------------------------
 */

declare module "@indago/hyper-json" {

  interface MoviesDataStore {
    items: Movie[];
  }
  interface Movie {
    id: string;
    title: string;
    cover: string;
    kind: "movie" | "series" | "anime";
    status: "watching" | "completed" | "backlog" | "dropped";
    genre: string;
    year?: number;
    rating?: number;
    description?: string;
    links?: {
      platform: string;
      url: string;
      label?: string;
    }[];
  }
}
