/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperJson Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperJson.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  schema.json file and rebuild the project.
 * --------------------------------------------------------
 */

declare module "@virtus/hyper-json" {
  interface PhotographyContentSchema {
    albums: Album[];
  }
  interface Album {
    id: string;
    name: string;
    description: string;
    date: string;
    location?: string;
    cover?: string;
    photos: Photo[];
  }
  interface Photo {
    id: string;
    src: string;
    alt: string;
    title?: string;
    description?: string;
    date?: string;
    location?: string;
    timeOfDay?: string;
    occasion?: string;
    tags?: string[];
  }
}
