/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperJson Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperJson.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  schema.json file and rebuild the project.
 * --------------------------------------------------------
 */

declare module "@indago/hyper-json" {

  interface BooksDataStore {
    items: Book[];
  }
  interface Book {
    id: string;
    title: string;
    author: string;
    cover: string;
    kind?: "book" | "manga" | "hq";
    status: "reading" | "finished" | "want-to-read" | "dropped";
    genre: string;
    rating?: number;
    /**
     * Override accent color as hex (e.g. '#fe0000')
     */
    accentColor?: string;
    description?: string;
    links?: {
      platform: string;
      url: string;
      label?: string;
    }[];
  }
}
