/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperJson Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperJson.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  schema.json file and rebuild the project.
 * --------------------------------------------------------
 */

declare module "@indago/hyper-json" {

  interface GamesDataStore {
    items: Game[];
  }
  interface Game {
    id: string;
    title: string;
    cover: string;
    status: "playing" | "completed" | "backlog" | "dropped";
    platform: string;
    genre: string;
    rating?: number;
    hoursPlayed?: number;
    /**
     * Override accent color as hex (e.g. '#fe0000')
     */
    accentColor?: string;
    description?: string;
    links?: {
      platform: string;
      url: string;
      label?: string;
    }[];
  }
}
