/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperJson Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperJson.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  schema.json file and rebuild the project.
 * --------------------------------------------------------
 */

declare module "@indago/hyper-json" {

  interface ProfileContentSchema {
    name: string;
    title: string;
    location?: string;
    email: string;
    website?: string;
    social: {
      github?: string;
      linkedin?: string;
    };
    experience?: ExperienceItem[];
    thesis?: {
      title?: string;
      subtitle?: string;
      institution?: string;
      year?: string;
      description?: string;
      technologies?: string[];
      links?: {
        source?: string;
        documentation?: string;
      };
    };
    hobbies?: string[];
  }
  interface ExperienceItem {
    id: string;
    role: string;
    company: string;
    period: string;
    location?: string;
    description: string;
    skills?: string[];
  }
}
