/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperDown Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperDown.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  frontmatter.json file and rebuild the project.
 * --------------------------------------------------------
 */

import type { ContentMeta } from "@virtus/hyper-down/types";

declare module "@virtus/hyper-down" {
  export interface RecipeMeta extends ContentMeta {
    title: string;
    description?: string;
    date: string;
    draft?: boolean;
    tags?: string[];
    cover?: string;
    cuisine?: string;
    mealType?: string;
    courseType?: string;
    difficulty?: "easy" | "medium" | "hard";
    prepTime?: string;
    cookTime?: string;
    servings?: string;
  }
}
