/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperJson Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperJson.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  schema.json file and rebuild the project.
 * --------------------------------------------------------
 */

declare module "@indago/hyper-json" {

  interface MusicDataStore {
    items: (Playlist | Favorite)[];
  }
  interface Playlist {
    id: string;
    title: string;
    description?: string;
    cover?: string;
    genre?: string;
    trackCount?: number;
    youtubeId: string;
  }
  interface Favorite {
    id: string;
    title: string;
    artist: string;
    album?: string;
    cover?: string;
    genre?: string;
    youtubeId: string;
  }
}
