/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperJson Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperJson.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  schema.json file and rebuild the project.
 * --------------------------------------------------------
 */

declare module "@virtus/hyper-json" {
  interface EducationContentSchema {
    items?: EducationItem[];
  }
  interface EducationItem {
    id: string;
    degree: string;
    institution: string;
    period: string;
    location: string;
    description: string;
    skills?: string[];
    accentColor?: "brand-500" | "brand-300";
  }
}
