/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperDown Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperDown.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  frontmatter.json file and rebuild the project.
 * --------------------------------------------------------
 */

import { createLazyRepository } from "@indago/hyper-down/server";

import type { ReviewMeta } from "@indago/hyper-down";

// Server-only DAO for the `review` collection — imported by `+data.ts`
// loaders (SSR-only), never by browser code. Lazily instantiated.
export const reviewRepository = createLazyRepository<ReviewMeta>({
  contentName: "review",
});
