/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperDown Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperDown.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  frontmatter.json file and rebuild the project.
 * --------------------------------------------------------
 */

import type { ContentMeta } from "@indago/hyper-down/types";

declare module "@indago/hyper-down" {
  export interface ReviewMeta extends ContentMeta {
    title: string;
    description?: string;
    date: string;
    draft?: boolean;
    tags?: string[];
    cover?: string;
    type?: "game" | "music" | "book" | "movie" | "other";
    kind?: "review" | "critique";
    subjectId?: string;
  }
}
