/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperJson Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperJson.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  schema.json file and rebuild the project.
 * --------------------------------------------------------
 */

declare module "@virtus/hyper-json" {
  interface SkillsContentSchema {
    clusters?: SkillCluster[];
  }
  interface SkillCluster {
    id: string;
    label: string;
    color: string;
    skills: Skill[];
  }
  interface Skill {
    name: string;
    level: number;
  }
}
