/* oxlint-disable */
/* oxfmt-disable */
/**
 * --------------------------------------------------------
 *  HyperJson Auto-Generated Types
 * --------------------------------------------------------
 *  This file was automatically generated by HyperJson.
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *
 *  To modify these types, update the corresponding
 *  schema.json file and rebuild the project.
 * --------------------------------------------------------
 */

declare module "@indago/hyper-json" {

  interface Projects {
    projects: ProjectContent[];
  }
  interface ProjectContent {
    name: string;
    description: string;
    url: string;
    language: string;
    languageColor: string;
    stars: number;
    topics: string[];
  }
}
